[package]
name = "origin-mind-mapper"
version = "0.1.0"
description = "一个私密、本地、键盘驱动的思维展开器"
authors = ["openAdam"]
edition = "2021"

[lib]
name = "origin_mind_mapper_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
